# Generated by Django 4.1.2 on 2022-10-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyUpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='playlist_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
