# Generated by Django 4.1.1 on 2022-10-30 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyUpApp', '0002_alter_event_playlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='rating1-5',
        ),
        migrations.RemoveConstraint(
            model_name='vendor',
            name='pricenonnegative',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='rating',
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratings',
            name='vendor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyUpApp.vendor'),
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='rating1-5'),
        ),
    ]
