# Generated by Django 4.1.1 on 2022-10-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyUpApp', '0003_ratings_remove_vendor_rating1-5_and_more'),
        ('PartyUpApp', '0004_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
    ]
