# Generated by Django 4.1.1 on 2022-10-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyUpApp', '0005_merge_20221031_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=160, null=True),
        ),
    ]
