# Generated by Django 4.1.1 on 2022-10-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyUpApp', '0006_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendor',
        ),
    ]
